services:
  preprocess:
    build:
      context: .
      dockerfile: Dockerfile.preprocess
    volumes:
      - ./data:/app/data  # Mount shared volume for the dataset
    command: python3 prepare_dataset.py  # Runs preprocessing and stops
  
  
  darts-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: darts_cpu_container
    volumes:
      - ./data:/app/data
      - ./src:/app
    command: python3 train_univariate.py

  darts-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: darts_gpu_container
    runtime: nvidia  # Ativa o suporte a GPU sem precisar de deploy.resources
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Configura a visibilidade de todas as GPUs
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./data:/app/data
      - ./src:/app
    command: python3 train_multivariate.py

  # test:
  #   image: nvidia/cuda:12.5.0-runtime-ubuntu22.04
  #   command: nvidia-smi
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]