FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04

# Instalar as ferramentas NVIDIA
RUN apt-get update && apt-get install -y --no-install-recommends \
    nvidia-utils-530 && \
    rm -rf /var/lib/apt/lists/*

CMD ["nvidia-smi", "-L"]